from config.setting import MEMORY, GPT_URL, DEEPSEEK_URL, GPT_API_KEY, DEEPSEEK_API_KEY, BING_URL, BING_API_KEY
from config.prompts import (SYSTEM_PROMPT, WST_PROMPT)

__all__ = ["SYSTEM_PROMPT", "WST_PROMPT", 
           "GPT_URL", "DEEPSEEK_URL", "GPT_API_KEY", "DEEPSEEK_API_KEY", "BING_URL", "BING_API_KEY", 
           "MEMORY"]